# Welcome to Jekyll!

# Website settings
title: "chanwoo"
description: "chanwoo's blog,use Jekyll and github pages."
keywords: "chanwoo,pcwpower,blog,Jekyll,github"
baseurl: "/"
# url: "https://pcwpower.github.io"
url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://127.0.0.1:4000/static/img/blog'

# author
author:
  name: 'Chanwoo'
  first_name: 'Park'
  last_name: 'Chanwoo'
  email: 'pcwpower@naver.com'
  facebook_username: 'pcwpower'
  instagram_username: 'pcwpower'
  github_username: 'pcwpower'
  head_img: 'static/img/landing/chan.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'My Projects &amp; Career'
  skills: 'Skills'
  blog: 'Blog'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'
  bookmark: 'Bookmark'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: pcwpower

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
